# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '20220919Authtest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseCore'
  pod 'FirebaseAuth'
	pod 'FirebaseFirestore'

  # Pods for 20220919Authtest

end
